# dynmap-mobs configuration
#
update:
  # Seconds between position updates for mobs
  period: 5.0
  # Seconds between position updates for vehicles
  vehicleperiod: 10.0
  # Round position to given unit
  resolution: 1.0
  # Make markers hidden when they are inside/underground/in shadows (#=light level: 0=full shadow,15=sky(disable hide))
  hideifshadow: 4
  # Make markers hidden when they are under cover (#=sky light level,0=underground,15=open to sky(disable hide))
  hideifundercover: 15

mobs:
  # Include creepers
  creeper: true
  # Include skeletons
  skeleton: true
  # Include zombies
  zombie: true
  # Include blazes
  blaze: true
  # Include ghasts
  ghast: true
  # Include silverfish
  silverfish: true
  # Include slimes
  slime: true
  # Include spiders
  spider: true
  # Include wolves
  wolf: true
  # Include zombie-pigmen
  zombiepigman: true
  # Include Enderdragon
  enderdragon: true
  # Include snow golems
  snowgolem: true
  # Include cave spider
  cavespider: true
  # Include spider jockey
  spiderjockey: true
  # Include enderman
  enderman: true
  # Include cows
  cow: false
  # Include pigs
  pig: false
  # Include chickens
  chicken: false
  # Include squids
  squid: false
  # Include sheep
  sheep: false
  # Include villagers
  villager: false
  # Include mooshroom
  mooshroom: false
  # Include tamed wolves
  tamedwolf: true  
  # Include ocelots
  ocelot: true
  # Include tamed cats
  cat: true
  # Include Iron golems
  golem: false
  # Include witches
  witch: false
  # Include wither skeletons
  witherskeleton: true
  # Include wither
  wither: true
  # Include zombie villager
  zombievillager: true
  # Include bats
  bat: false
  # Include horses (vanilla MC)
  vanillahorse: false
  # Mo'Creatures Mobs
  horse: false
  fireogre: false
  caveogre: false
  ogre: false
  boar: false
  polarbear: false
  bear: false
  duck: false
  bigcat: false
  deer: false
  wildwolf: false
  flamewraith: false
  wraith: false
  bunny: false
  bird: false
  fox: false
  werewolf: false
  shark: false
  dolphin: false
  fishy: false
  kitty: false
  hellrat: false
  rat: false
  mouse: false
  scorpion: false
  turtle: false
  crocodile: false
  ray: false
  jellyfish: false
  goat: false
  snake: false
  ostrich: false
  minestuckImp: false
  minestuckOgre: false
  minestuckGiclops: false
  minestuckBasilisk: false
  prospitianPawn: false
  prospitianBishop: false
  dersitePawn: false
  dersiteBishop: false

vehicles:
  # Specific minecart types
  explosive-minecart: false
  hopper-minecart: false
  powered-minecart: false
  spawner-minecart: false
  storage-minecart: false
  minecart: false
  # Boats
  boat: false
  
layer:
  name: "Mobs"
  # Make mobs layer hidden by default
  hidebydefault: false
  # ordering priority in layer menu (low goes before high - default is 0)
  layerprio: 10
  # (optional) if true, use tiny marker icons (8x8) - default is 16x16
  tinyicons: false
  # (optional) if true, don't show labels on mob icons
  nolabels: false
  # (optional) set minimum zoom level when mob icons should be visible (0=default, any zoom)
  minzoom: 0
  # (optional) include coordinate in label for icon
  inc-coord: false
  
vehiclelayer:
  name: "Vehicles"
  hidebydefault: false
  # ordering priority in layer menu (low goes before high - default is 0)
  layerprio: 11
  # (optional) if true, use tiny marker icons (8x8) - default is 16x16
  tinyicons: false
  # (optional) if true, don't show labels on mob icons
  nolabels: false
  # (optional) set minimum zoom level when mob icons should be visible (0=default, any zoom)
  minzoom: 0
  # (optional) include coordinate in label for icon
  inc-coord: false
  
